module

public import Eggshell.Value

@[expose] public section

namespace Eggshell

inductive UnionScope where
  | run (inquiry : Value)
  | workspace (workspace : Value)
  deriving DecidableEq, BEq

/-- A Union is admissible only when it cannot substitute Exact authority. -/
structure UnionEdge where
  left : Value
  right : Value
  scope : UnionScope
  exactAuthority : Value.SameExactFootprint left right

namespace UnionEdge

def samePair (edge : UnionEdge) (left right : Value) : Bool :=
  (edge.left == left && edge.right == right) ||
    (edge.left == right && edge.right == left)

def newPair (edges : List UnionEdge) (left right : Value) : Bool :=
  left != right && !edges.any (fun edge => edge.samePair left right)

def swap (edge : UnionEdge) : UnionEdge where
  left := edge.right
  right := edge.left
  scope := edge.scope
  exactAuthority := Value.sameExactFootprint_symm edge.exactAuthority

@[simp]
theorem swap_left (edge : UnionEdge) : edge.swap.left = edge.right := rfl

@[simp]
theorem swap_right (edge : UnionEdge) : edge.swap.right = edge.left := rfl

@[simp]
theorem swap_swap (edge : UnionEdge) : edge.swap.swap = edge := by
  cases edge
  simp [swap]

end UnionEdge

mutual

/--
The semantic equality generated by scoped Union edges and Apply congruence.
Exact arguments must be literally equal; only Semantic arguments recurse.
-/
inductive Equivalent (edges : List UnionEdge) : Value → Value → Prop where
  | refl (value) : Equivalent edges value value
  | union (edge) : edge ∈ edges → Equivalent edges edge.left edge.right
  | symm : Equivalent edges left right → Equivalent edges right left
  | trans : Equivalent edges left middle → Equivalent edges middle right →
      Equivalent edges left right
  | apply (operator) : RefsEquivalent edges leftArgs rightArgs →
      Equivalent edges (.apply operator leftArgs) (.apply operator rightArgs)

inductive RefsEquivalent (edges : List UnionEdge) : Refs → Refs → Prop where
  | nil : RefsEquivalent edges .nil .nil
  | semantic : Equivalent edges left right → RefsEquivalent edges lefts rights →
      RefsEquivalent edges (.semantic left lefts) (.semantic right rights)
  | exact : RefsEquivalent edges lefts rights →
      RefsEquivalent edges (.exact value lefts) (.exact value rights)

end

theorem Equivalent.exactAuthority {edges left right}
    (equivalent : Equivalent edges left right) :
    Value.SameExactFootprint left right :=
  Equivalent.rec
    (motive_1 := fun left right _ => Value.SameExactFootprint left right)
    (motive_2 := fun left right _ => ∀ exact,
      exact ∈ Value.refsExactFootprint left ↔
        exact ∈ Value.refsExactFootprint right)
    (fun value => Value.sameExactFootprint_refl value)
    (fun edge _ => edge.exactAuthority)
    (fun _ induction => Value.sameExactFootprint_symm induction)
    (fun _ _ leftMiddle middleRight =>
      Value.sameExactFootprint_trans leftMiddle middleRight)
    (fun _ _ induction => induction)
    (by intro exact; simp [Value.refsExactFootprint])
    (fun _ _ head tail exact => by
      simp only [Value.refsExactFootprint, List.mem_append]
      exact or_congr (head exact) (tail exact))
    (fun _ tail exact => by
      simp only [Value.refsExactFootprint, List.mem_cons, List.mem_append]
      exact or_congr Iff.rfl (tail exact))
    equivalent

end Eggshell
